# Base image with Java
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Copy Maven project
COPY . .

# Build WebGoat
RUN ./mvnw clean package -DskipTests

# Expose port
EXPOSE 8080

# Run WebGoat
CMD ["java","-jar","webgoat-server/target/webgoat-server-8.2.0.jar"]
